---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
library(flexdashboard)
```




```{r reading in data}
airbnb_data = read_csv("nyc_airbnb.csv") %>%
  clean_names() %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude) %>%
  mutate(rating = review_scores_location / 2) %>%
  filter(!is.na(rating)) 
```



```{r creating widgets}
boros = airbnb_data %>% distinct(boro) %>% pull()

# selectInput widget
selectInput("boro_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")

max_price = 1000
min_price = airbnb_data %>% distinct(price) %>% min()
  
# sliderInput widget
sliderInput("price_range", label = h3("Choose price range"), min = min_price, 
        max = max_price, value = c(100, 400))

room_choice = airbnb_data %>% distinct(room_type) %>% pull()

# radioButtons widget
radioButtons("room_choice", label = h3("Choose room type"),
    choices = room_choice, 
    selected = "Entire home/apt")


```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}


```


Row
-----------------------------------------------------------------------

### Chart A

```{r}

#renderPlotly indicates to R that the values of what is in the chart depend on user input
renderPlotly({ 
  airbnb_data %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  filter(boro == input$boro_choice, 
         price %in% input$price_range[1]:input$price_range[2], 
         room_type == input$room_choice)
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
})

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

